import { ClerkProvider } from "@clerk/nextjs";
import StarsCanvas from "../components/starbg";
import Navbar from "./navbar";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>{children}</body>
      </html>
  </ClerkProvider>
    
  )
}
